<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class PublicExperience extends BaseConfig
{
    /**
     * Canonical Indonesian paths and their English equivalents.
     *
     * Detail routes are resolved separately by the helper so slugs and IDs
     * remain stable in both languages.
     *
     * @var array<string, string>
     */
    public array $localizedPaths = [
        '/' => '/en',
        '/home' => '/en/home',
        '/profil' => '/en/about',
        '/program' => '/en/programs',
        '/pengurus' => '/en/team',
        '/kegiatan' => '/en/activities',
        '/kontak' => '/en/contact',
        '/kontak/kirim' => '/en/contact/send',
        '/login' => '/en/login',
    ];

    /**
     * Public interface copy that is not managed by the structured CMS.
     *
     * @var array<string, array{id: string, en: string}>
     */
    public array $copy = [
        'preferences.label' => [
            'id' => 'Bahasa dan tema',
            'en' => 'Language and theme',
        ],
        'preferences.open' => [
            'id' => 'Buka pilihan bahasa dan tema',
            'en' => 'Open language and theme settings',
        ],
        'preferences.close' => [
            'id' => 'Tutup pilihan',
            'en' => 'Close settings',
        ],
        'preferences.language' => [
            'id' => 'Bahasa',
            'en' => 'Language',
        ],
        'preferences.theme' => [
            'id' => 'Tema',
            'en' => 'Theme',
        ],
        'preferences.auto' => [
            'id' => 'Otomatis',
            'en' => 'Auto',
        ],
        'preferences.ivory' => [
            'id' => 'Ivory',
            'en' => 'Ivory',
        ],
        'preferences.midnight' => [
            'id' => 'Midnight',
            'en' => 'Midnight',
        ],
        'preferences.auto_note' => [
            'id' => 'Mengikuti perangkat',
            'en' => 'Follows your device',
        ],
        'preferences.saved' => [
            'id' => 'Pilihan tersimpan di perangkat ini.',
            'en' => 'Your choice is saved on this device.',
        ],
        'accessibility.return_to_intro' => [
            'id' => 'Kembali ke Introducing {organization}',
            'en' => 'Return to the {organization} Introducing experience',
        ],
        'accessibility.open_map' => [
            'id' => 'Buka lokasi {organization} di Google Maps',
            'en' => 'Open the {organization} location in Google Maps',
        ],
        'accessibility.carousel_item' => [
            'id' => 'Tampilkan pengurus ke-{number}',
            'en' => 'Show team member {number}',
        ],
        'accessibility.carousel_previous' => [
            'id' => 'Lihat pengurus sebelumnya',
            'en' => 'Show previous team member',
        ],
        'accessibility.carousel_next' => [
            'id' => 'Lihat pengurus berikutnya',
            'en' => 'Show next team member',
        ],
        'accessibility.carousel_list' => [
            'id' => 'Daftar profil pengurus',
            'en' => 'Team profile list',
        ],
        'accessibility.gallery_dialog' => [
            'id' => 'Galeri dokumentasi kegiatan',
            'en' => 'Activity documentation gallery',
        ],
        'accessibility.gallery_position' => [
            'id' => 'Foto {current} dari {total}',
            'en' => 'Photo {current} of {total}',
        ],
        'accessibility.gallery_open' => [
            'id' => 'Buka foto {number} di galeri',
            'en' => 'Open photo {number} in the gallery',
        ],
        'accessibility.gallery_close' => [
            'id' => 'Tutup galeri',
            'en' => 'Close gallery',
        ],
        'accessibility.gallery_previous' => [
            'id' => 'Foto sebelumnya',
            'en' => 'Previous photo',
        ],
        'accessibility.gallery_next' => [
            'id' => 'Foto berikutnya',
            'en' => 'Next photo',
        ],
        'accessibility.navigation_open' => [
            'id' => 'Buka menu navigasi',
            'en' => 'Open navigation menu',
        ],
        'accessibility.navigation_close' => [
            'id' => 'Tutup menu navigasi',
            'en' => 'Close navigation menu',
        ],
        'navigation.home' => [
            'id' => 'Beranda',
            'en' => 'Home',
        ],
        'navigation.profile' => [
            'id' => 'Tentang',
            'en' => 'About',
        ],
        'navigation.programs' => [
            'id' => 'Program',
            'en' => 'Programs',
        ],
        'navigation.activities' => [
            'id' => 'Kegiatan',
            'en' => 'Activities',
        ],
        'navigation.officials' => [
            'id' => 'Pengurus',
            'en' => 'Team',
        ],
        'navigation.contact' => [
            'id' => 'Kontak',
            'en' => 'Contact',
        ],
        'navigation.portal' => [
            'id' => 'Portal Pengurus',
            'en' => 'Team Portal',
        ],
        'navigation.footer_profile' => [
            'id' => 'Tentang GARDA 01',
            'en' => 'About GARDA 01',
        ],
        'navigation.footer_programs' => [
            'id' => 'Pilar Program',
            'en' => 'Program Pillars',
        ],
        'navigation.footer_contact' => [
            'id' => 'Kontak & Kolaborasi',
            'en' => 'Contact & Collaboration',
        ],
        'seo.introducing_title' => [
            'id' => 'GARDA 01 — Introducing | Generasi Aktif Randugarut',
            'en' => 'GARDA 01 — Introducing | Active Generation of Randugarut',
        ],
        'seo.introducing_description' => [
            'id' => 'Gerbang digital GARDA 01, Generasi Aktif Randugarut: Guyub, Bergerak, dan Berdampak dari RW 01.',
            'en' => 'The digital gateway to GARDA 01, the Active Generation of Randugarut: united, in motion, and making an impact from RW 01.',
        ],
        'seo.home_title' => [
            'id' => 'GARDA 01 | Generasi Aktif Randugarut',
            'en' => 'GARDA 01 | Active Generation of Randugarut',
        ],
        'seo.home_description' => [
            'id' => 'Website resmi GARDA 01, Generasi Aktif Randugarut, Karang Taruna RW 01 Kelurahan Randugarut.',
            'en' => 'The official website of GARDA 01, the youth organization of RW 01, Randugarut.',
        ],
        'seo.profile_title' => [
            'id' => 'Profil GARDA 01 | Generasi Aktif Randugarut',
            'en' => 'About GARDA 01 | Active Generation of Randugarut',
        ],
        'seo.profile_description' => [
            'id' => 'Mengenal GARDA 01 — Generasi Aktif Randugarut, identitas Karang Taruna RW 01 Kelurahan Randugarut.',
            'en' => 'Meet GARDA 01—the Active Generation of Randugarut and the youth organization of RW 01.',
        ],
        'seo.programs_title' => [
            'id' => 'Program GARDA 01 | Karang Taruna RW 01',
            'en' => 'GARDA 01 Programs | RW 01 Youth Organization',
        ],
        'seo.programs_description' => [
            'id' => 'Pilar program GARDA 01 dalam bidang sosial, lingkungan, olahraga, kreativitas, usaha, pendidikan, dan keagamaan.',
            'en' => 'GARDA 01 program pillars across social action, environment, sports, creativity, enterprise, education, and community values.',
        ],
        'seo.activities_title' => [
            'id' => 'Kegiatan GARDA 01 | Randugarut',
            'en' => 'GARDA 01 Activities | Randugarut',
        ],
        'seo.activities_description' => [
            'id' => 'Dokumentasi kegiatan GARDA 01, Karang Taruna RW 01 Kelurahan Randugarut.',
            'en' => 'Stories and documentation from GARDA 01, the youth organization of RW 01, Randugarut.',
        ],
        'seo.officials_title' => [
            'id' => 'Pengurus GARDA 01 | Karang Taruna RW 01',
            'en' => 'GARDA 01 Team | RW 01 Youth Organization',
        ],
        'seo.officials_description' => [
            'id' => 'Struktur dan profil pengurus GARDA 01, Karang Taruna RW 01 Kelurahan Randugarut.',
            'en' => 'The structure and team behind GARDA 01, the youth organization of RW 01, Randugarut.',
        ],
        'seo.contact_title' => [
            'id' => 'Kontak dan Kolaborasi | GARDA 01',
            'en' => 'Contact and Collaboration | GARDA 01',
        ],
        'seo.contact_description' => [
            'id' => 'Hubungi GARDA 01 untuk kolaborasi kegiatan, program sosial, lingkungan, kepemudaan, usaha, media, dan pemberdayaan masyarakat.',
            'en' => 'Contact GARDA 01 for activities, social initiatives, environmental work, youth programs, enterprise, media, and community collaboration.',
        ],
        'activity.not_found' => [
            'id' => 'Kegiatan tidak ditemukan.',
            'en' => 'Activity not found.',
        ],
        'contact.success' => [
            'id' => 'Pesan berhasil dikirim. Tim GARDA 01 akan menindaklanjutinya.',
            'en' => 'Your message has been sent. The GARDA 01 team will follow up.',
        ],
        'contact.success_generic' => [
            'id' => 'Pesan Anda berhasil dikirim.',
            'en' => 'Your message has been sent.',
        ],
        'contact.rate_limit' => [
            'id' => 'Terlalu banyak pesan dikirim dari jaringan ini. Tunggu beberapa menit lalu coba kembali.',
            'en' => 'Too many messages were sent from this network. Please wait a few minutes and try again.',
        ],
        'contact.session_limit' => [
            'id' => 'Mohon tunggu sebentar sebelum mengirim pesan berikutnya.',
            'en' => 'Please wait a moment before sending another message.',
        ],
        'contact.label_name' => [
            'id' => 'Nama lengkap',
            'en' => 'Full name',
        ],
        'contact.label_email' => [
            'id' => 'Alamat email',
            'en' => 'Email address',
        ],
        'contact.label_phone' => [
            'id' => 'Nomor WhatsApp',
            'en' => 'WhatsApp number',
        ],
        'contact.label_category' => [
            'id' => 'Kategori pesan',
            'en' => 'Message category',
        ],
        'contact.label_subject' => [
            'id' => 'Subjek',
            'en' => 'Subject',
        ],
        'contact.label_message' => [
            'id' => 'Isi pesan',
            'en' => 'Message',
        ],
        'auth.rate_limit' => [
            'id' => 'Terlalu banyak percobaan masuk. Tunggu beberapa menit lalu coba kembali.',
            'en' => 'Too many sign-in attempts. Please wait a few minutes and try again.',
        ],
        'auth.invalid' => [
            'id' => 'Email atau kata sandi tidak sesuai.',
            'en' => 'The email address or password is incorrect.',
        ],
        'auth.inactive' => [
            'id' => 'Akun Anda sedang tidak aktif.',
            'en' => 'Your account is currently inactive.',
        ],
        'auth.role_missing' => [
            'id' => 'Peran akun belum dikonfigurasi. Hubungi administrator.',
            'en' => 'This account role has not been configured. Contact an administrator.',
        ],
        'auth.logout' => [
            'id' => 'Anda telah keluar dari GARDA 01 Portal.',
            'en' => 'You have signed out of the GARDA 01 Portal.',
        ],
        'auth.label_email' => [
            'id' => 'Alamat email',
            'en' => 'Email address',
        ],
        'auth.label_password' => [
            'id' => 'Kata sandi',
            'en' => 'Password',
        ],
        'validation.required' => [
            'id' => '{field} wajib diisi.',
            'en' => 'The {field} field is required.',
        ],
        'validation.valid_email' => [
            'id' => '{field} harus berupa alamat email yang valid.',
            'en' => 'The {field} field must contain a valid email address.',
        ],
        'validation.min_length' => [
            'id' => '{field} minimal terdiri dari {param} karakter.',
            'en' => 'The {field} field must be at least {param} characters long.',
        ],
        'validation.max_length' => [
            'id' => '{field} tidak boleh melebihi {param} karakter.',
            'en' => 'The {field} field cannot exceed {param} characters in length.',
        ],
        'validation.in_list' => [
            'id' => 'Pilihan {field} tidak valid.',
            'en' => 'The selected {field} is invalid.',
        ],
    ];

    /**
     * Exact public copy translations used by the server-side compatibility
     * layer. Content not listed here remains unchanged, which prevents names,
     * locations, and visitor-provided data from being altered accidentally.
     *
     * @var array<string, string>
     */
    public array $englishDictionary = [
        'Beranda' => 'Home',
        'Tentang' => 'About',
        'Tentang GARDA 01' => 'About GARDA 01',
        'Program' => 'Programs',
        'Pilar Program' => 'Program Pillars',
        'Kegiatan' => 'Activities',
        'Pengurus' => 'Team',
        'Kontak' => 'Contact',
        'Kontak & Kolaborasi' => 'Contact & Collaboration',
        'Portal Pengurus' => 'Team Portal',
        'Portal Internal' => 'Internal Portal',
        'Karang Taruna RW 01 • Kelurahan Randugarut' => 'RW 01 Youth Organization • Randugarut',
        'Karang Taruna RW 01 Kelurahan Randugarut' => 'RW 01 Randugarut Youth Organization',
        'Karang Taruna RW 01 Randugarut' => 'RW 01 Randugarut Youth Organization',
        'RW 01 Kelurahan Randugarut' => 'RW 01, Randugarut',
        'Wilayah RW 01 Kelurahan Randugarut, Kecamatan Tugu, Kota Semarang.' => 'The RW 01 area of Randugarut, Tugu District, Semarang City.',
        'Kelurahan Randugarut' => 'Randugarut Urban Village',
        'Kecamatan Tugu' => 'Tugu District',
        'Kota Semarang' => 'Semarang City',
        'Jawa Tengah' => 'Central Java',
        'Generasi Aktif Randugarut' => 'Active Generation of Randugarut',
        'GENERASI AKTIF RANDUGARUT' => 'ACTIVE GENERATION OF RANDUGARUT',
        'GARDA 01 / GENERASI AKTIF RANDUGARUT' => 'GARDA 01 / ACTIVE GENERATION OF RANDUGARUT',
        'Guyub • Bergerak • Berdampak' => 'United • In Motion • Making an Impact',
        'GUYUB • BERGERAK • BERDAMPAK' => 'UNITED • IN MOTION • MAKING AN IMPACT',
        'Karang Taruna RW 01' => 'RW 01 Youth Organization',
        "Guyub dalam kebersamaan.\nBergerak melalui karya.\nBerdampak bagi lingkungan." => "United through togetherness.\nMoving through meaningful work.\nCreating impact for our community.",
        'Ruang tumbuh dan kolaborasi pemuda RW 01 dalam kegiatan sosial, lingkungan, olahraga, kreativitas, pendidikan, usaha, dan pemberdayaan masyarakat.' => 'A space for the youth of RW 01 to grow and collaborate through social action, environmental work, sports, creativity, education, enterprise, and community empowerment.',
        'Lihat Gerak Kami' => 'See Our Movement',
        'Kenali GARDA 01' => 'Meet GARDA 01',
        'Gerak Terbaru' => 'Latest Movement',
        'Lihat dokumentasi' => 'View Documentation',
        'Dokumentasi kegiatan akan segera ditampilkan.' => 'Activity documentation will be available soon.',
        'RT Terhubung' => 'Connected RT',
        'Wilayah pemuda yang terdata dan terlibat.' => 'Youth areas represented and involved.',
        'Pengurus Aktif' => 'Active Team',
        'Penggerak organisasi dan program GARDA 01.' => 'The people driving GARDA 01 and its programs.',
        'Kegiatan Terlaksana' => 'Completed Activities',
        'Gerakan yang telah selesai dan terdokumentasi.' => 'Completed actions with documented outcomes.',
        'Ruang kontribusi pemuda dalam berbagai bidang.' => 'Spaces for youth contribution across different fields.',
        'Semangat GARDA 01' => 'The GARDA 01 Spirit',
        'Bertumbuh melalui kebersamaan dan tindakan nyata' => 'Growing through togetherness and tangible action',
        'GARDA 01 hadir bukan sekadar sebagai struktur organisasi, tetapi sebagai ruang bagi pemuda untuk saling menguatkan, menciptakan karya, dan memberi manfaat bagi lingkungan.' => 'GARDA 01 is more than an organization structure. It is a space where young people strengthen one another, create meaningful work, and benefit their community.',
        'Guyub' => 'United',
        'Menyatukan pemuda, warga, dan berbagai unsur masyarakat melalui kebersamaan yang sehat, terbuka, dan saling menguatkan.' => 'Bringing youth, residents, and community partners together through healthy, open, and mutually supportive relationships.',
        'Bergerak' => 'In Motion',
        'Mengubah gagasan menjadi kegiatan nyata melalui kolaborasi, tanggung jawab, dan keberanian mengambil peran.' => 'Turning ideas into real activities through collaboration, responsibility, and the courage to take part.',
        'Berdampak' => 'Making Impact',
        'Menghadirkan program yang relevan, terdokumentasi, dan memberikan manfaat yang dapat dirasakan lingkungan.' => 'Delivering relevant, documented programs whose benefits can be felt across the community.',
        'Dari kepedulian menjadi aksi' => 'Turning care into action',
        'Setiap pilar GARDA 01 menjadi ruang bagi pemuda untuk berkontribusi sesuai minat, kemampuan, dan kebutuhan lingkungan.' => 'Each GARDA 01 pillar gives young people room to contribute according to their interests, abilities, and community needs.',
        'Seluruh Program' => 'All Programs',
        'Pelajari program' => 'Explore Program',
        'Program GARDA 01 belum tersedia.' => 'GARDA 01 programs are not available yet.',
        'Cerita Dampak' => 'Impact Story',
        'Gerakan bersama pemuda dan warga untuk menghadirkan manfaat nyata, memperkuat kepedulian, serta menjaga kebersamaan di lingkungan RW 01 Randugarut.' => 'A shared movement of youth and residents creating tangible benefits, strengthening care, and sustaining togetherness in RW 01 Randugarut.',
        'Baca Cerita Kegiatan' => 'Read the Activity Story',
        'Jejak Gerak GARDA 01' => 'GARDA 01 in Motion',
        'Kegiatan terbaru' => 'Latest Activities',
        'Dokumentasi kegiatan, kolaborasi, dan kontribusi pemuda GARDA 01 bagi lingkungan.' => 'Stories of GARDA 01 activities, collaborations, and youth contributions to the community.',
        'Seluruh Kegiatan' => 'All Activities',
        'Lihat Dokumentasi' => 'View Documentation',
        'Dokumentasi kegiatan terbaru belum tersedia.' => 'The latest activity documentation is not available yet.',
        'Bergerak Bersama' => 'Move Together',
        'Mari hadirkan lebih banyak dampak untuk lingkungan' => 'Let us create more impact for our community',
        'GARDA 01 terbuka untuk berkolaborasi dengan warga, komunitas, UMKM, lembaga pendidikan, pemerintah, serta mitra sosial dalam kegiatan yang bermanfaat bagi masyarakat.' => 'GARDA 01 welcomes collaboration with residents, communities, small businesses, educational institutions, government, and social partners on activities that benefit the public.',
        'Hubungi GARDA 01' => 'Contact GARDA 01',
        'Lihat Program' => 'View Programs',
        'Terbuka untuk kolaborasi:' => 'Open to collaboration:',
        "Sosial dan kemanusiaan\nLingkungan dan kebersihan\nOlahraga dan kepemudaan\nPendidikan dan keterampilan\nUsaha produktif pemuda\nMedia dan kreativitas" => "Social and humanitarian action\nEnvironment and cleanliness\nSports and youth development\nEducation and skills\nYouth enterprise\nMedia and creativity",
        'Tentang Organisasi' => 'About the Organization',
        "Generasi Aktif\nRandugarut" => "Active Generation\nof Randugarut",
        'GARDA 01 merupakan identitas publik Karang Taruna RW 01 Kelurahan Randugarut sebagai ruang kolaborasi, pengembangan pemuda, dan kontribusi nyata bagi lingkungan.' => 'GARDA 01 is the public identity of the RW 01 Randugarut youth organization—a space for collaboration, youth development, and tangible community contribution.',
        'Kenali Pengurus' => 'Meet the Team',
        'Siapa Kami' => 'Who We Are',
        'Tumbuh bersama pemuda dan warga RW 01' => 'Growing with the youth and residents of RW 01',
        'Karang Taruna RW 01 Kelurahan Randugarut merupakan organisasi sosial kepemudaan yang menjadi wadah partisipasi, pengembangan, dan kolaborasi pemuda di lingkungan RW 01.' => 'The RW 01 Randugarut youth organization is a community institution that supports youth participation, development, and collaboration across RW 01.',
        'Melalui GARDA 01, organisasi membangun identitas yang lebih mudah dikenal sekaligus tetap mempertahankan nama resmi Karang Taruna RW 01 dalam administrasi, legalitas, dan tata kelola organisasi.' => 'Through GARDA 01, the organization has built a more recognizable public identity while retaining the official RW 01 youth organization name for administration, legal matters, and governance.',
        'Menjadi organisasi pemuda yang guyub, aktif, adaptif, dan menghadirkan dampak nyata bagi lingkungan.' => 'To become a united, active, and adaptive youth organization that creates tangible impact for the community.',
        "Membangun kebersamaan dan partisipasi pemuda di seluruh wilayah RW 01.\nMenyelenggarakan kegiatan sosial, lingkungan, olahraga, pendidikan, usaha, dan kreativitas.\nMengembangkan tata kelola organisasi yang tertib, transparan, dan terdokumentasi.\nMembangun kolaborasi dengan warga, komunitas, lembaga, pemerintah, dan mitra." => "Build youth participation and togetherness across RW 01.\nDeliver social, environmental, sports, education, enterprise, and creative activities.\nDevelop orderly, transparent, and documented organizational governance.\nBuild collaboration with residents, communities, institutions, government, and partners.",
        'Menjaga kebersamaan, rasa memiliki, dan hubungan yang sehat antarpemuda serta warga.' => 'Nurturing togetherness, a sense of belonging, and healthy relationships among youth and residents.',
        'Mengubah gagasan menjadi program, kegiatan, kolaborasi, dan karya yang nyata.' => 'Turning ideas into real programs, activities, collaborations, and creative work.',
        'Memastikan setiap langkah memberi manfaat dan perubahan positif bagi lingkungan.' => 'Ensuring every step brings value and positive change to the community.',
        'Kenali tujuh pilar gerakan GARDA 01' => 'Discover the seven pillars of the GARDA 01 movement',
        'Setiap pilar menjadi ruang bagi pemuda untuk belajar, berkolaborasi, dan menghasilkan kontribusi nyata.' => 'Each pillar gives young people space to learn, collaborate, and create tangible contributions.',
        "Bergerak bersama\nGARDA 01" => "Move forward with\nGARDA 01",
        'Sampaikan gagasan, undangan, tawaran kolaborasi, kebutuhan sosial, maupun informasi kegiatan kepada Karang Taruna RW 01 Randugarut.' => 'Share ideas, invitations, collaboration opportunities, community needs, or activity information with the RW 01 Randugarut youth organization.',
        "Generasi Aktif Randugarut\nKarang Taruna RW 01" => "Active Generation of Randugarut\nRW 01 Youth Organization",
        'Gunakan kanal resmi berikut untuk menyampaikan kebutuhan, undangan, atau peluang kolaborasi.' => 'Use these official channels to share a need, invitation, or collaboration opportunity.',
        'Belum dicantumkan oleh pengurus.' => 'Not yet provided by the team.',
        'Isi informasi dengan lengkap agar tim GARDA 01 dapat menindaklanjuti pesan dengan tepat.' => 'Provide complete information so the GARDA 01 team can respond appropriately.',
        'Pesan akan masuk ke Portal Pengurus GARDA 01.' => 'Your message will be delivered to the GARDA 01 Team Portal.',
        "Program sosial dan kemanusiaan\nKegiatan lingkungan dan kebersihan\nOlahraga serta kepemudaan\nPendidikan dan keterampilan\nMedia, desain, dan dokumentasi\nUsaha produktif dan UMKM" => "Social and humanitarian programs\nEnvironmental and clean-up activities\nSports and youth development\nEducation and skills\nMedia, design, and documentation\nYouth enterprise and small businesses",
        'Basis gerakan pemuda GARDA 01 di wilayah Kelurahan Randugarut, Kecamatan Tugu, Kota Semarang.' => 'GARDA 01 is rooted in Randugarut, Tugu District, Semarang City.',
        'Untuk kondisi darurat, layanan pemerintahan, keamanan, atau kesehatan, silakan menghubungi instansi resmi yang berwenang.' => 'For emergencies, government services, security, or health matters, please contact the appropriate official authority.',
        'Generasi Aktif Randugarut. Ruang kolaborasi pemuda untuk tumbuh, bergerak, dan memberi dampak bagi lingkungan.' => 'The Active Generation of Randugarut—a youth collaboration space to grow, move, and make an impact in the community.',
        'Website resmi Karang Taruna RW 01 Kelurahan Randugarut.' => 'The official website of the RW 01 Randugarut youth organization.',
        'Navigasi' => 'Navigation',
        'Organisasi & Lokasi' => 'Organization & Location',
        'Hubungi Kami' => 'Contact Us',
        'Sampaikan undangan, gagasan, informasi, atau tawaran kolaborasi melalui kanal resmi GARDA 01.' => 'Share an invitation, idea, information, or collaboration opportunity through GARDA 01 official channels.',
        'Buka di Google Maps' => 'Open in Google Maps',
        'Dokumentasi Organisasi' => 'Organization Documentation',
        'Kegiatan GARDA 01' => 'GARDA 01 Activities',
        'Kumpulan program, agenda, dan dokumentasi aktivitas Karang Taruna RW 01 Kelurahan Randugarut.' => 'Programs, events, and activity documentation from the RW 01 Randugarut youth organization.',
        'Sosialisasi' => 'Community Outreach',
        'Kerja Bakti RW 01' => 'RW 01 Community Clean-up',
        'Kerja Bakti' => 'Community Clean-up',
        'Berjualan' => 'Community Bazaar',
        'Lingkungan RW 01' => 'RW 01 Community Area',
        'Lapangan Randugarut' => 'Randugarut Field',
        'Sawah' => 'Rice Fields',
        'Mewarnai' => 'Coloring Activity',
        'Kita bersama-sama melukis wajah si Pria Solo' => 'Together, we painted a portrait of Pria Solo.',
        'Pria Solo dua periode' => 'Pria Solo for two terms.',
        'Adik-adik' => 'Children',
        'Semua' => 'All',
        'Direncanakan' => 'Planned',
        'Selesai' => 'Completed',
        'Dibatalkan' => 'Cancelled',
        'Lihat Detail' => 'View Details',
        'Belum ada kegiatan pada kategori ini.' => 'There are no activities in this category yet.',
        'Pilih kategori program lain atau tampilkan seluruh dokumentasi kegiatan GARDA 01.' => 'Choose another program category or view all GARDA 01 activity documentation.',
        'Lihat Semua Kegiatan' => 'View All Activities',
        'Kenali program GARDA 01' => 'Discover GARDA 01 Programs',
        'Setiap kegiatan menjadi bagian dari pilar sosial, lingkungan, olahraga, kreativitas, usaha, pendidikan, atau keagamaan.' => 'Every activity is connected to a pillar of social action, environment, sports, creativity, enterprise, education, or community values.',
        'Tujuh pilar program yang menjadi ruang gerak pemuda dalam bidang sosial, lingkungan, olahraga, kreativitas, usaha, pendidikan, dan keagamaan.' => 'Seven program pillars that give young people space to act across social initiatives, environment, sports, creativity, enterprise, education, and community values.',
        'Lihat Seluruh Pilar' => 'View All Pillars',
        'Tujuh ruang kontribusi pemuda' => 'Seven spaces for youth contribution',
        'Setiap pilar memiliki fokus yang jelas, tetapi tetap bergerak dalam satu identitas GARDA 01.' => 'Each pillar has a clear focus while moving within one shared GARDA 01 identity.',
        'Lihat pelaksanaan kegiatan GARDA 01' => 'See GARDA 01 programs in action',
        'Program menjadi arah gerak, sedangkan kegiatan menjadi dokumentasi pelaksanaannya di lingkungan masyarakat.' => 'Programs set the direction; activities document how that direction becomes real work in the community.',
        'Lihat Kegiatan' => 'View Activities',
        'Peduli' => 'Care',
        'Hijau' => 'Green',
        'Olahraga' => 'Sports',
        'Kreatif' => 'Creative',
        'Belajar' => 'Learning',
        'Berkah' => 'Values',
        'GARDA 01 Peduli' => 'GARDA 01 Care',
        'GARDA 01 Hijau' => 'GARDA 01 Green',
        'GARDA 01 Kreatif' => 'GARDA 01 Creative',
        'GARDA 01 Belajar' => 'GARDA 01 Learning',
        'GARDA 01 Berkah' => 'GARDA 01 Values',
        'GARDA 01 Berbagi' => 'GARDA 01 Sharing',
        'Aksi Berbagi Ramadan' => 'Ramadan Sharing Action',
        'Dukungan Sosial Warga' => 'Community Social Support',
        'GARDA 01 Bersih' => 'GARDA 01 Clean',
        'Gerakan Lingkungan Hijau' => 'Green Environment Movement',
        'Olahraga Bersama Pemuda' => 'Youth Sports Together',
        'Turnamen RW 01' => 'RW 01 Tournament',
        'Dokumentasi GARDA 01' => 'GARDA 01 Documentation',
        'Media Kreatif Pemuda' => 'Youth Creative Media',
        'Stan Usaha Pemuda' => 'Youth Enterprise Booth',
        'Bazar GARDA 01' => 'GARDA 01 Bazaar',
        'Pelatihan Administrasi Pemuda' => 'Youth Administration Training',
        'Literasi Digital GARDA' => 'GARDA Digital Literacy',
        'Kelas Keterampilan Pemuda' => 'Youth Skills Class',
        'Ramadan Bersama GARDA' => 'Ramadan with GARDA',
        'Peringatan Hari Besar Islam' => 'Islamic Holiday Observances',
        'Pemuda Berbagi Berkah' => 'Youth Sharing Blessings',
        'Ruang lingkup gerakan' => 'Scope of Action',
        'Program dan Kampanye' => 'Programs and Campaigns',
        'Contoh pelaksanaan' => 'Examples in Action',
        'Lihat dokumentasi kegiatan →' => 'View activity documentation →',
        'Bergerak bersama untuk RW 01' => 'Moving together for RW 01',
        'GARDA 01 terbuka untuk kolaborasi bersama warga, komunitas, lembaga, dan mitra sosial.' => 'GARDA 01 welcomes collaboration with residents, communities, institutions, and social partners.',
        'Belum ditetapkan' => 'Not yet set',
        'Pengurus Karang Taruna' => 'Youth Organization Team',
        'Mengenal para pengurus yang menjalankan fungsi koordinasi, administrasi, keuangan, kegiatan, dan pelayanan kepemudaan di lingkungan RW 01 Kelurahan Randugarut.' => 'Meet the team responsible for coordination, administration, finance, activities, and youth services across RW 01 Randugarut.',
        'Susunan organisasi ditampilkan berdasarkan urutan dan jabatan yang tercatat pada sistem internal.' => 'The organization structure follows the order and roles recorded in the internal system.',
        'Ketua' => 'Chair',
        'Wakil Ketua' => 'Vice Chair',
        'Sekretaris' => 'Secretary',
        'Bendahara' => 'Treasurer',
        'Seksi Olahraga' => 'Sports Division',
        'SEKSI OLAHRAGA' => 'SPORTS DIVISION',
        'Inti' => 'Core Team',
        'Tampan dan Berani' => 'Confident and Courageous',
        'Koordinator Utama' => 'Lead Coordinator',
        'Pimpinan Organisasi' => 'Organization Leadership',
        'Pengurus Inti' => 'Core Team',
        'Bidang/Seksi' => 'Division',
        'Data struktur pengurus belum tersedia.' => 'The team structure is not available yet.',
        'Geser ke samping untuk melihat profil pengurus lainnya.' => 'Swipe sideways to view more team profiles.',
        'Lihat pengurus sebelumnya' => 'View previous team member',
        'Daftar profil pengurus' => 'Team profile list',
        'Foto' => 'Photo',
        'Periode' => 'Term',
        'Pengurus Karang Taruna RW 01 Kelurahan Randugarut.' => 'A team member of the RW 01 Randugarut youth organization.',
        'Lihat pengurus berikutnya' => 'View next team member',
        'Profil pengurus belum tersedia.' => 'Team profiles are not available yet.',
        'Hubungi GARDA 01 untuk menyampaikan informasi kegiatan, aspirasi pemuda, atau kesempatan kolaborasi bagi lingkungan.' => 'Contact GARDA 01 to share activity information, youth aspirations, or opportunities to collaborate for the community.',
        'Kembali ke Kegiatan' => 'Back to Activities',
        'Informasi Pelaksanaan' => 'Activity Information',
        'Ringkasan Kegiatan' => 'Activity Summary',
        'Hasil Kegiatan' => 'Activity Outcomes',
        'Semua Kegiatan' => 'All Activities',
        'Kolaborasi dan Kemitraan' => 'Collaboration and Partnerships',
        'Undangan atau Kegiatan' => 'Invitations or Activities',
        'Sosial dan Kemanusiaan' => 'Social and Humanitarian',
        'Usaha dan UMKM' => 'Enterprise and Small Businesses',
        'Media dan Publikasi' => 'Media and Publications',
        'Informasi Umum' => 'General Information',
        'Form kontak dinonaktifkan selama review eksternal.' => 'The contact form is disabled during external review.',
        'Peduli sesama, hadir untuk warga.' => 'Care for others, show up for the community.',
        'Pilar sosial yang berfokus pada kepedulian, bantuan warga, kegiatan kemanusiaan, dan aksi berbagi.' => 'A social pillar focused on care, community support, humanitarian activities, and sharing.',
        'GARDA 01 Peduli menjadi ruang gerak pemuda untuk menghadirkan dukungan nyata bagi warga dan lingkungan sosial. Program dijalankan melalui aksi berbagi, bantuan sosial, dukungan bagi warga yang membutuhkan, serta kolaborasi kemanusiaan.' => 'GARDA 01 Care gives young people space to provide tangible support for residents and the wider community through sharing, social assistance, support for those in need, and humanitarian collaboration.',
        'Aksi sosial dan kemanusiaan' => 'Social and humanitarian action',
        'Bantuan dan dukungan bagi warga' => 'Community assistance and support',
        'Kampanye berbagi' => 'Sharing campaigns',
        'Kolaborasi sosial masyarakat' => 'Community social collaboration',
        'Lingkungan' => 'Environment',
        'Lingkungan terawat, warga lebih sehat.' => 'A cared-for environment, a healthier community.',
        'Pilar lingkungan untuk kebersihan, penghijauan, pengelolaan sampah, dan kepedulian terhadap ruang bersama.' => 'An environmental pillar for cleanliness, greening, waste management, and care for shared spaces.',
        'GARDA 01 Hijau mendorong keterlibatan pemuda dalam menjaga kebersihan dan kualitas lingkungan RW 01 melalui kerja bakti, penghijauan, edukasi lingkungan, dan gerakan pengelolaan sampah.' => 'GARDA 01 Green engages young people in protecting the cleanliness and quality of RW 01 through community work, greening, environmental education, and waste management.',
        'Kerja bakti lingkungan' => 'Community clean-up',
        'Penghijauan wilayah' => 'Neighborhood greening',
        'Pengelolaan sampah' => 'Waste management',
        'Edukasi lingkungan' => 'Environmental education',
        'Olahraga dan Kepemudaan' => 'Sports and Youth',
        'Aktif bergerak, solid bersama.' => 'Active in motion, united together.',
        'Pilar olahraga dan aktivitas kepemudaan untuk membangun kesehatan, kebersamaan, dan sportivitas.' => 'A sports and youth pillar that builds health, togetherness, and sportsmanship.',
        'GARDA 01 Sport menjadi ruang aktivitas olahraga dan kebugaran pemuda melalui latihan bersama, turnamen, pertandingan persahabatan, dan dukungan terhadap kegiatan olahraga masyarakat.' => 'GARDA 01 Sport creates space for youth sports and fitness through shared practice, tournaments, friendly matches, and support for community sports.',
        'Turnamen dan pertandingan' => 'Tournaments and matches',
        'Latihan olahraga rutin' => 'Regular sports practice',
        'Aktivitas kebugaran pemuda' => 'Youth fitness activities',
        'Kolaborasi komunitas olahraga' => 'Sports community collaboration',
        'Media dan Kreativitas' => 'Media and Creativity',
        'Kreativitas pemuda untuk cerita yang bermakna.' => 'Youth creativity for meaningful stories.',
        'Pilar media, desain, dokumentasi, seni, publikasi, dan pengembangan kreativitas pemuda.' => 'A pillar for media, design, documentation, arts, publishing, and youth creativity.',
        'GARDA 01 Creative mengembangkan kemampuan pemuda dalam desain, dokumentasi, publikasi, seni, fotografi, video, dan pengelolaan media sosial organisasi.' => 'GARDA 01 Creative develops youth skills in design, documentation, publishing, arts, photography, video, and organization social media.',
        'Desain dan publikasi' => 'Design and publishing',
        'Dokumentasi foto dan video' => 'Photo and video documentation',
        'Media sosial organisasi' => 'Organization social media',
        'Seni dan kreativitas pemuda' => 'Youth arts and creativity',
        'Usaha dan Kemandirian' => 'Enterprise and Independence',
        'Produktif, mandiri, dan bertumbuh.' => 'Productive, independent, and growing.',
        'Pilar usaha pemuda, bazar, penjualan, dan penggalangan dana produktif untuk mendukung kemandirian organisasi.' => 'A pillar for youth enterprise, bazaars, sales, and productive fundraising that supports organizational independence.',
        'GARDA 01 Enterprise menjadi ruang belajar dan pengembangan usaha produktif pemuda. Program ini mendorong pengalaman berjualan, pengelolaan modal, pemasaran, serta penguatan sumber dana organisasi.' => 'GARDA 01 Enterprise is a learning space for developing youth-led ventures through sales experience, capital management, marketing, and stronger organizational funding.',
        'Usaha produktif pemuda' => 'Youth enterprise',
        'Bazar dan penjualan' => 'Bazaars and sales',
        'Pelatihan kewirausahaan' => 'Entrepreneurship training',
        'Penggalangan dana produktif' => 'Productive fundraising',
        'Pendidikan dan Keterampilan' => 'Education and Skills',
        'Belajar bersama, berkembang bersama.' => 'Learning together, growing together.',
        'Pilar pendidikan, pelatihan, literasi digital, administrasi, dan pengembangan keterampilan pemuda.' => 'An education pillar for training, digital literacy, administration, and youth skills.',
        'GARDA 01 Belajar mendukung pengembangan kapasitas pemuda melalui pelatihan, literasi digital, administrasi organisasi, pendidikan informal, dan kegiatan berbagi pengetahuan.' => 'GARDA 01 Learning develops youth capacity through training, digital literacy, organization administration, informal education, and knowledge sharing.',
        'Pelatihan keterampilan' => 'Skills training',
        'Literasi digital' => 'Digital literacy',
        'Administrasi organisasi' => 'Organization administration',
        'Pendidikan dan mentoring' => 'Education and mentoring',
        'Keagamaan' => 'Community Values',
        'Tumbuh dalam nilai, bergerak dalam kebaikan.' => 'Grow in values, move through kindness.',
        'Pilar kegiatan keagamaan, spiritual, dan penguatan nilai kebersamaan masyarakat.' => 'A pillar for faith-based activities, spirituality, and shared community values.',
        'GARDA 01 Berkah mengembangkan kegiatan keagamaan dan spiritual yang mempererat kebersamaan pemuda dan warga melalui kajian, peringatan hari besar, kegiatan Ramadan, serta dukungan kegiatan keagamaan lingkungan.' => 'GARDA 01 Values develops faith-based and spiritual activities that strengthen youth and community ties through learning gatherings, holiday observances, Ramadan activities, and neighborhood initiatives.',
        'Kegiatan keagamaan pemuda' => 'Youth faith activities',
        'Peringatan hari besar' => 'Holiday observances',
        'Program Ramadan' => 'Ramadan programs',
        'Kolaborasi kegiatan spiritual' => 'Spiritual activity collaboration',
        'Portal Manajemen' => 'Management Portal',
        'Website Publik' => 'Public Website',
        'Kembali ke Website GARDA 01' => 'Back to the GARDA 01 Website',
        'Buka menu navigasi' => 'Open navigation menu',
        'Navigasi utama' => 'Main navigation',
        'Navigasi footer' => 'Footer navigation',
        'Navigasi legal footer' => 'Footer legal navigation',
        'Langsung ke konten utama' => 'Skip to main content',
        'Progres perjalanan' => 'Journey progress',
        'Progres membaca halaman' => 'Page reading progress',
        'Navigator bab halaman' => 'Page chapter navigator',
        'Buka navigator bab halaman' => 'Open page chapter navigator',
        'Daftar bab halaman' => 'Page chapter list',
        'Di halaman ini' => 'On this page',
        'Pembuka' => 'Opening',
        'Jelajah' => 'Explore',
        'Tekan G' => 'Press G',
        'Tutup navigator' => 'Close navigator',
        'Jangan hanya melihat.' => 'Do more than look.',
        'Pilih arah,' => 'Choose a direction,',
        'temukan gerak.' => 'find your movement.',
        'Direktori situs' => 'Site directory',
        'Kembali ke Introducing' => 'Back to Introducing',
        'Mulai dari sini' => 'Start here',
        'Kenali siapa kami' => 'Meet who we are',
        'Tujuh ruang kontribusi' => 'Seven spaces to contribute',
        'Mendalami satu pilar' => 'Explore one pillar',
        'Jejak gerak nyata' => 'A trail of real action',
        'Cerita Gerak' => 'Movement Story',
        'Satu aksi, satu cerita' => 'One action, one story',
        'Manusia di balik gerakan' => 'The people behind the movement',
        'Mari bergerak bersama' => 'Let us move together',
        'Lewati intro' => 'Skip intro',
        'Sebuah gerbang digital dari sudut kecil Randugarut' => 'A digital gateway from a small corner of Randugarut',
        'Bukan sekadar situs organisasi.' => 'More than an organization website.',
        'Ini adalah jejak dari mereka yang memilih untuk bergerak.' => 'This is the trail of those who choose to move.',
        'Gulir perlahan' => 'Scroll slowly',
        'perjalanan dimulai di bawah' => 'the journey begins below',
        'Kami mulai dengan satu keyakinan' => 'We begin with one conviction',
        'KAMI' => 'WE ARE',
        'BUKAN' => 'NOT',
        'PENONTON.' => 'SPECTATORS.',
        'Di lingkungan kecil, dampak tidak harus menunggu sesuatu yang besar. Ia dimulai dari menyapa, membantu, berkarya—lalu mengajak yang lain ikut bergerak.' => 'In a small community, impact does not have to wait for something big. It begins by showing up, helping, creating—and inviting others to move with us.',
        'GUYUB' => 'UNITED',
        'BERGERAK' => 'IN MOTION',
        'BERDAMPAK' => 'MAKING IMPACT',
        'Titik nol kami' => 'Our point zero',
        'DARI' => 'FROM',
        'KAMI MULAI.' => 'WE BEGIN.',
        'Kami tidak datang dengan janji untuk mengubah dunia dalam semalam. Kami datang dengan kesediaan untuk hadir—dan mengubah apa yang paling dekat terlebih dahulu.' => 'We do not arrive with a promise to change the world overnight. We arrive ready to be present—and to change what is closest first.',
        'RT TERHUBUNG' => 'CONNECTED RT',
        'RUANG KONTRIBUSI' => 'SPACES TO CONTRIBUTE',
        'GERAKAN BERSAMA' => 'ONE SHARED MOVEMENT',
        'Ekosistem gerakan' => 'Movement ecosystem',
        'TUJUH RUANG.' => 'SEVEN SPACES.',
        'SATU DENYUT.' => 'ONE PULSE.',
        'Setiap orang punya cara berbeda untuk berdampak. Temukan ruangmu, bawa energimu, dan biarkan semuanya saling terhubung.' => 'Everyone has a different way to make an impact. Find your space, bring your energy, and let every effort connect.',
        'Intro selesai. Cerita sebenarnya baru dimulai.' => 'The intro is over. The real story is just beginning.',
        'PILIH' => 'CHOOSE',
        'ARAHMU.' => 'YOUR DIRECTION.',
        'Navigasi situs utama' => 'Main site navigation',
        'Tujuan terpilih' => 'Selected destination',
        'Masuk ke Beranda' => 'Enter Home',
        'Area internal organisasi' => 'Internal organization area',
        'Memasuki ruang GARDA 01...' => 'Entering the GARDA 01 space...',
        'BERANDA' => 'HOME',
        'Identitas Resmi' => 'Official Identity',
        'Identitas yang kami bawa bersama' => 'The identity we carry together',
        'Nama Organisasi' => 'Organization Name',
        'Identitas Publik' => 'Public Identity',
        'Kepanjangan' => 'Full Name',
        'Wilayah' => 'Area',
        'Slogan' => 'Slogan',
        'Arah Organisasi' => 'Our Direction',
        'Visi dan misi GARDA 01' => 'GARDA 01 Vision and Mission',
        'Visi' => 'Vision',
        'Misi' => 'Mission',
        'Nilai Organisasi' => 'Organization Values',
        'Budaya yang kami bangun bersama' => 'The culture we build together',
        'Ruang Kontribusi' => 'Spaces to Contribute',
        'Jelajahi Program' => 'Explore Programs',
        'Pilar Gerakan' => 'Movement Pillars',
        'Arsitektur Program' => 'Program Architecture',
        'Dari Program Menjadi Aksi' => 'From Programs to Action',
        'Fokus Program' => 'Program Focus',
        'Kolaborasi' => 'Collaboration',
        'Lihat Program Lainnya' => 'View Other Programs',
        'Dokumentasi Kegiatan' => 'Activity Documentation',
        'Dokumentasi Resmi' => 'Official Documentation',
        'Dokumentasi Utama' => 'Main Documentation',
        'Informasi pelaksanaan' => 'Activity Information',
        'Nama Kegiatan' => 'Activity Name',
        'Tanggal' => 'Date',
        'Lokasi' => 'Location',
        'Status' => 'Status',
        'Cerita dan pelaksanaan kegiatan' => 'Activity Story and Delivery',
        'Dampak' => 'Impact',
        'Dampak dan capaian' => 'Impact and Outcomes',
        'Kegiatan terkait' => 'Related Activities',
        'Lihat gerakan GARDA 01 lainnya' => 'Explore More GARDA 01 Activities',
        'Struktur Organisasi' => 'Organization Structure',
        'Pengurus tercatat' => 'Registered team members',
        'Periode kepengurusan' => 'Team term',
        'Aktif · Solid · Bertanggung Jawab' => 'Active · United · Accountable',
        'Diagram Organisasi' => 'Organization Diagram',
        'Struktur Kepengurusan' => 'Team Structure',
        'Profil Pengurus' => 'Team Profiles',
        'Orang-orang di balik organisasi' => 'The people behind the organization',
        'Terhubung dengan Pengurus' => 'Connect with the Team',
        'Sampaikan undangan, gagasan, atau peluang kolaborasi' => 'Share an invitation, idea, or collaboration opportunity',
        'Kontak dan Kolaborasi' => 'Contact and Collaboration',
        'Bergerak bersama' => 'Move together',
        'Kanal Resmi Organisasi' => 'Official Organization Channels',
        'Kanal Resmi' => 'Official Channels',
        'Pilih cara paling nyaman untuk terhubung' => 'Choose the easiest way to connect',
        'Email Resmi' => 'Official Email',
        'Lokasi Organisasi' => 'Organization Location',
        'Kirim Pesan' => 'Send a Message',
        'Apa yang ingin Anda sampaikan?' => 'What would you like to share?',
        'Nama Lengkap' => 'Full Name',
        'Nama Anda' => 'Your name',
        'Nomor WhatsApp' => 'WhatsApp Number',
        'Contoh: 081234567890' => 'Example: 081234567890',
        'Opsional' => 'Optional',
        'Kategori Pesan' => 'Message Category',
        'Subjek' => 'Subject',
        'Ringkasan kebutuhan atau tujuan Anda' => 'A short summary of your need or goal',
        'Isi Pesan' => 'Message',
        'Tuliskan informasi selengkap mungkin.' => 'Please provide as much useful information as possible.',
        'Ruang Kolaborasi' => 'Collaboration Space',
        'Kami terbuka untuk bergerak bersama' => 'We are open to moving forward together',
        'Wilayah Organisasi' => 'Organization Area',
        'Buka Google Maps' => 'Open Google Maps',
        'Catatan' => 'Note',
        'Program sosial dan kemanusiaan' => 'Social and humanitarian programs',
        'Kegiatan lingkungan dan kebersihan' => 'Environmental and clean-up activities',
        'Olahraga serta kepemudaan' => 'Sports and youth development',
        'Pendidikan dan keterampilan' => 'Education and skills',
        'Media, desain, dan dokumentasi' => 'Media, design, and documentation',
        'Usaha produktif dan UMKM' => 'Youth enterprise and small businesses',
        'Masuk ke akun Anda' => 'Sign in to your account',
        'Gunakan akun pengurus yang telah terdaftar untuk mengakses sistem manajemen organisasi.' => 'Use a registered team account to access the organization management system.',
        'Akses khusus pengurus' => 'Team access only',
        'Masukkan kata sandi' => 'Enter your password',
        'Tampilkan kata sandi' => 'Show password',
        'Sembunyikan kata sandi' => 'Hide password',
        'Memverifikasi akun...' => 'Verifying account...',
        'Alamat Email' => 'Email Address',
        'Kata Sandi' => 'Password',
        'Masuk ke Portal' => 'Sign in to Portal',
        'Akses internal organisasi' => 'Internal organization access',
        'Jangan membagikan email, kata sandi, maupun akses portal kepada pihak yang tidak berwenang.' => 'Do not share your email, password, or portal access with unauthorized parties.',
        'Ruang kerja digital' => 'The digital workspace',
        'pengurus GARDA 01' => 'for the GARDA 01 team',
        'Kelola organisasi, kegiatan, keuangan, publikasi, dokumentasi, dan komunikasi warga dalam satu portal yang tertib dan terintegrasi.' => 'Manage the organization, activities, finances, publications, documentation, and community communication in one structured, integrated portal.',
        'Terhubung dalam kebersamaan.' => 'Connected through togetherness.',
        'Mengubah rencana menjadi aksi.' => 'Turning plans into action.',
        'Menghadirkan manfaat nyata.' => 'Creating tangible benefits.',
        'Buka lokasi GARDA 01 di Google Maps' => 'Open GARDA 01 on Google Maps',
        'Profil Organisasi' => 'Organization Profile',
        'Buka Dokumentasi Lengkap' => 'Open Full Documentation',
        'Tentang Kegiatan' => 'About This Activity',
        'Dokumentasi Lainnya' => 'More Documentation',
        'Kegiatan lain yang berada dalam ruang gerak GARDA 01.' => 'More activities within the GARDA 01 movement.',
        'Jelajahi dokumentasi kegiatan dan tujuh pilar program Karang Taruna RW 01 Randugarut.' => 'Explore activity stories and the seven program pillars of the RW 01 Randugarut youth organization.',
        '← Kembali ke Kegiatan' => '← Back to Activities',
        '← Seluruh Program' => '← All Programs',
        'Kirim email' => 'Send Email',
        'Buka WhatsApp' => 'Open WhatsApp',
        'Lihat lokasi' => 'View Location',
        'Website' => 'Website',
        'Kecamatan' => 'District',
        'Gerak Pemuda' => 'Youth Movement',
        'Dokumentasi kegiatan GARDA 01' => 'GARDA 01 Activity Documentation',
        'Pilar' => 'Pillar',
        '← Kembali ke Website' => '← Back to Website',
        'Kembali ke website GARDA 01' => 'Back to the GARDA 01 website',
        'Dokumentasi kegiatan GARDA 01 Randugarut.' => 'GARDA 01 Randugarut activity documentation.',
        'Program GARDA 01 tidak ditemukan.' => 'The GARDA 01 program was not found.',
        'Program GARDA 01 Randugarut.' => 'A GARDA 01 Randugarut program.',
        'Basis gerakan pemuda GARDA 01 di wilayah Randugarut.' => 'GARDA 01 youth movement based in Randugarut.',
        'Setiap hari, respons menyesuaikan ketersediaan pengurus.' => 'Available daily; response times follow team availability.',
        'Pesan akan ditinjau oleh pengurus dan ditindaklanjuti sesuai kebutuhan.' => 'The team will review your message and follow up as needed.',
        'Halo GARDA 01, saya ingin menghubungi pengurus.' => 'Hello GARDA 01, I would like to contact the team.',
    ];
}
